In [1]:
import numpy as np

A = np.array([[7, -1], [6, 3]])
A

array([[ 7, -1],
       [ 6,  3]])

## Determinant of Square Matrix

In [2]:
np.linalg.det(A)

27.0

In [3]:
A = np.array([[1,2,2],[-1, 3, 5], [2, 1, 3]])
A

array([[ 1,  2,  2],
       [-1,  3,  5],
       [ 2,  1,  3]])

In [4]:
np.linalg.det(A)

16.000000000000007

## Inverse of Square Matrix

In [5]:
from numpy.linalg import inv

In [6]:
A

array([[ 1,  2,  2],
       [-1,  3,  5],
       [ 2,  1,  3]])

In [7]:
A_inverse = inv(A)
A_inverse

array([[ 0.25  , -0.25  ,  0.25  ],
       [ 0.8125, -0.0625, -0.4375],
       [-0.4375,  0.1875,  0.3125]])

## Matrix Maths

In [8]:
A = np.array([[2, 3],
            [1, 0]])
B = np.array([[3, 4],
             [5, 4]])
A + B

array([[5, 7],
       [6, 4]])

In [9]:
np.dot(A, B)

array([[21, 20],
       [ 3,  4]])

In [10]:
np.dot(B, A)

array([[10,  9],
       [14, 15]])