In [1]:
import os
import numpy as np
import pandas as pd

In [3]:
df_gym = pd.read_csv('GYM.csv')
df_gym

number_people  day_of_week  is_weekend  is_holiday  temperature  \
0                 37            4           0           0        71.76   
1                 45            4           0           0        71.76   
2                 40            4           0           0        71.76   
3                 44            4           0           0        71.76   
4                 45            4           0           0        71.76   
...              ...          ...         ...         ...          ...   
62179             23            5           1           0        61.07   
62180             21            5           1           0        61.07   
62181             25            5           1           0        56.71   
62182             18            5           1           0        56.71   
62183             23            5           1           0        56.71   

       is_start_of_semester  is_during_semester  month  hour  
0                         0                   0      8    17  
1                         0                   0      8    17  
2                         0                   0      8    17  
3                         0                   0      8    17  
4                         0                   0      8    17  
...                     ...                 ...    ...   ...  
62179                     0                   1      3    18  
62180                     0                   1      3    18  
62181                     0                   1      3    19  
62182                     0                   1      3    19  
62183                     0                   1      3    19  

[62184 rows x 9 columns]

In [4]:
df_gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   number_people         62184 non-null  int64  
 1   day_of_week           62184 non-null  int64  
 2   is_weekend            62184 non-null  int64  
 3   is_holiday            62184 non-null  int64  
 4   temperature           62184 non-null  float64
 5   is_start_of_semester  62184 non-null  int64  
 6   is_during_semester    62184 non-null  int64  
 7   month                 62184 non-null  int64  
 8   hour                  62184 non-null  int64  
dtypes: float64(1), int64(8)
memory usage: 4.3 MB


In [5]:
df_gym.columns

Index(['number_people', 'day_of_week', 'is_weekend', 'is_holiday',
       'temperature', 'is_start_of_semester', 'is_during_semester', 'month',
       'hour'],
      dtype='object')

In [7]:
sel_cols = ['day_of_week', 'is_weekend', 'is_holiday',
       'temperature', 'is_start_of_semester', 'is_during_semester', 'month',
       'hour']

In [20]:
X = df_gym[df_gym.columns]

In [21]:
y = df_gym['number_people']
X.shape, y.shape

((62184, 9), (62184,))

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [23]:
X_std = StandardScaler().fit_transform(X)

In [24]:
X_std

array([[ 0.34939892,  0.50956119, -0.6280507 , ..., -1.39393832,
         0.16260365,  0.70911589],
       [ 0.70199512,  0.50956119, -0.6280507 , ..., -1.39393832,
         0.16260365,  0.70911589],
       [ 0.48162249,  0.50956119, -0.6280507 , ..., -1.39393832,
         0.16260365,  0.70911589],
       ...,
       [-0.17949539,  1.01036016,  1.59222814, ...,  0.71739186,
        -1.28875789,  1.0068423 ],
       [-0.48801707,  1.01036016,  1.59222814, ...,  0.71739186,
        -1.28875789,  1.0068423 ],
       [-0.26764444,  1.01036016,  1.59222814, ...,  0.71739186,
        -1.28875789,  1.0068423 ]])

In [25]:
cov_mat = np.cov(X_std, rowvar=False)
cov_mat

array([[ 1.00001608e+00, -1.62064466e-01, -1.73960610e-01,
        -4.82501246e-02,  3.73333302e-01,  1.82685836e-01,
         3.35355754e-01, -9.78551214e-02,  5.52058322e-01],
       [-1.62064466e-01,  1.00001608e+00,  7.91350923e-01,
        -7.58632581e-02,  1.11689106e-02, -1.17822146e-02,
        -4.82370614e-03,  1.55589363e-02, -1.91430511e-03],
       [-1.73960610e-01,  7.91350923e-01,  1.00001608e+00,
        -3.18993471e-02,  2.06736733e-02, -1.66460432e-02,
        -3.61277725e-02,  8.46248251e-03, -5.17297084e-04],
       [-4.82501246e-02, -7.58632581e-02, -3.18993471e-02,
         1.00001608e+00, -8.85280154e-02, -1.48581472e-02,
        -7.07995743e-02, -9.49438154e-02,  2.84321058e-03],
       [ 3.73333302e-01,  1.11689106e-02,  2.06736733e-02,
        -8.85280154e-02,  1.00001608e+00,  9.32433629e-02,
         1.52478347e-01,  6.31255958e-02,  1.85123709e-01],
       [ 1.82685836e-01, -1.17822146e-02, -1.66460432e-02,
        -1.48581472e-02,  9.32433629e-02,  1.000016

In [26]:
print('Covariance matrix \n')

eigen_values, eigen_vectors = np.linalg.eig(cov_mat)
print('Eigen values:\n', eigen_values)
print('Eigen vectors:\n', eigen_vectors)


Covariance matrix 

Eigen values:
 [2.04958658 1.73199109 0.31504025 0.20666435 1.17411649 1.11866801
 0.69783664 0.79125894 0.91498239]
Eigen vectors:
 [[-5.71152792e-01  2.47109706e-01  7.50836945e-01  1.65994561e-02
   1.00551975e-01  1.35279968e-01  6.64999204e-02 -1.25609699e-01
  -8.84398290e-03]
 [ 3.80575058e-01  5.82582976e-01  9.32549054e-02 -7.05155884e-01
   7.10835914e-02 -6.77040924e-04  2.27651935e-02 -5.44348829e-02
   3.58281754e-02]
 [ 3.88550675e-01  5.72849404e-01  7.25343785e-02  7.07023948e-01
   1.03269728e-01  2.36153197e-02  4.72057551e-03 -6.87774453e-03
   6.66027621e-02]
 [ 3.16629844e-02 -1.66061463e-01  3.06779246e-02 -3.82780840e-02
   4.96132764e-01  1.23824941e-01 -3.61734012e-03  1.78383434e-01
   8.22010115e-01]
 [-3.19177070e-01  3.08677723e-01 -2.11164415e-01 -2.27814858e-02
  -1.75131931e-01  9.32764545e-02  1.50926379e-01  8.33985881e-01
  -7.19328009e-03]
 [-2.08429918e-01  1.44791044e-01 -4.43669942e-02 -3.11300758e-03
   2.43275900e-01 -6.77688

In [27]:
tot = sum(eigen_values) #all of it
tot

9.000144734091311

In [28]:
exp_var = [(i/tot)*100 for i in sorted(eigen_values, reverse=True)]
print('Variance Explained:', exp_var)

Variance Explained: [22.772818046476694, 19.244035975884273, 13.045528929756603, 12.429444680996433, 10.166307480372193, 8.791624628465163, 7.753615735242588, 3.500390905479974, 2.2962336173260893]


In [29]:
eigen_values/tot*100


array([22.77281805, 19.24403598,  3.50039091,  2.29623362, 13.04552893,
       12.42944468,  7.75361574,  8.79162463, 10.16630748])

In [30]:
cum_exp_var = np.cumsum(exp_var)
print('Cumulative variance explained', cum_exp_var)

Cumulative variance explained [ 22.77281805  42.01685402  55.06238295  67.49182763  77.65813511
  86.44975974  94.20337548  97.70376638 100.        ]
